import Foundation

struct UpdaterSettings: Equatable {
    var weekday = 1      // launchd semantics: 1=Mon ... 7=Sun
    var hour = 9
    var minute = 0
    var notifyEnabled = true
    var proxyHost = "127.0.0.1"
    var proxyPort = "7890"
    var manageFlClash = true
    var flclashBundle = "com.follow.clash"

    static let weekdayNamesZh = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]
    static let weekdayNamesEn = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    var weekdayName: String {
        (isZh ? Self.weekdayNamesZh : Self.weekdayNamesEn)[max(0, min(6, weekday - 1))]
    }
}

enum SettingsStore {
    static func load() -> UpdaterSettings {
        var s = UpdaterSettings()
        guard let text = try? String(contentsOf: Paths.conf, encoding: .utf8) else { return s }
        for raw in text.split(whereSeparator: \.isNewline) {
            let parts = raw.split(separator: "=", maxSplits: 1)
                .map { String($0).trimmingCharacters(in: .whitespaces) }
            guard parts.count == 2 else { continue }
            let v = parts[1].trimmingCharacters(in: CharacterSet(charactersIn: "\""))
            switch parts[0] {
            case "PROXY_HOST": if !v.isEmpty { s.proxyHost = v }
            case "PROXY_PORT": if !v.isEmpty { s.proxyPort = v }
            case "FLCLASH_BUNDLE": if !v.isEmpty { s.flclashBundle = v }
            case "MANAGE_FLCLASH": s.manageFlClash = v == "1"
            case "NOTIFY": s.notifyEnabled = v == "1"
            case "WEEKDAY": if let n = Int(v), (1...7).contains(n) { s.weekday = n }
            case "HOUR": if let n = Int(v), (0...23).contains(n) { s.hour = n }
            case "MINUTE": if let n = Int(v), (0...59).contains(n) { s.minute = n }
            default: break
            }
        }
        return s
    }

    static func save(_ s: UpdaterSettings) throws {
        let text = """
        # Generated by RimeIceUpdater; hand edits are allowed.
        PROXY_HOST="\(s.proxyHost)"
        PROXY_PORT="\(s.proxyPort)"
        FLCLASH_BUNDLE="\(s.flclashBundle)"
        MANAGE_FLCLASH="\(s.manageFlClash ? "1" : "0")"
        NOTIFY="\(s.notifyEnabled ? "1" : "0")"
        WEEKDAY="\(s.weekday)"
        HOUR="\(s.hour)"
        MINUTE="\(s.minute)"
        """
        try FileManager.default.createDirectory(at: Paths.scriptsDir, withIntermediateDirectories: true)
        try text.write(to: Paths.conf, atomically: true, encoding: .utf8)
    }
}
